name: App

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 📩 Grab the code
        uses: actions/checkout@v3

      - name: 🏗️ Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: 🔨 Compile the app
        run: bash build.sh compile

      - name: 🆙 Upload the app jar
        uses: actions/upload-artifact@v4
        with:
          name: Caffeinated.jar
          path: app/core/target/Caffeinated.jar

  build_windows:
    needs: [build]
    runs-on: [self-hosted, Windows, x64, code-sign]
    steps:
      - name: 📩 Grab the code
        uses: actions/checkout@v3

      - name: 📩 Download the app artifact
        uses: actions/download-artifact@v4
        with:
          name: Caffeinated.jar
          path: app/core/target

      - name: 🏗️ Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: 📦 Create the Windows bundle
        run: bash build.sh dist-windows

      - name: 🆙 Upload the Windows x86_64 bundle to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Casterlabs-Caffeinated-windows-x86_64.zip
          path: dist/artifacts/Casterlabs-Caffeinated-windows-x86_64.zip

  bundle_macos:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: 📩 Grab the code
        uses: actions/checkout@v3

      - name: 📩 Download the app artifact
        uses: actions/download-artifact@v4
        with:
          name: Caffeinated.jar
          path: app/core/target

      - name: 🏗️ Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: 📦 Create the macOS bundles
        run: bash build.sh dist-macos

      - name: 🆙 Upload the macOS x86_64 bundle to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Casterlabs-Caffeinated-macos-x86_64.tar.gz
          path: dist/artifacts/Casterlabs-Caffeinated-macos-x86_64.tar.gz

  bundle_gnulinux:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: 📩 Grab the code
        uses: actions/checkout@v3

      - name: 📩 Download the app artifact
        uses: actions/download-artifact@v4
        with:
          name: Caffeinated.jar
          path: app/core/target

      - name: 🏗️ Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: 📦 Create the GNU/Linux bundles
        run: bash build.sh dist-linux

      - name: 🆙 Upload the GNU/Linux x86_64 bundle to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Casterlabs-Caffeinated-gnulinux-x86_64.tar.gz
          path: dist/artifacts/Casterlabs-Caffeinated-gnulinux-x86_64.tar.gz

  release:
    needs: [build_windows, bundle_macos, bundle_gnulinux]
    runs-on: ubuntu-latest
    steps:
      - name: 📩 Download all the artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/artifacts

      - name: 릴리스에 업로드
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/artifacts/Casterlabs-Caffeinated-windows-x86_64.zip/Casterlabs-Caffeinated-windows-x86_64.zip,dist/artifacts/Casterlabs-Caffeinated-macos-x86_64.tar.gz/Casterlabs-Caffeinated-macos-x86_64.tar.gz,dist/artifacts/Casterlabs-Caffeinated-gnulinux-x86_64.tar.gz/Casterlabs-Caffeinated-gnulinux-x86_64.tar.gz"
          tag: "dev-${{ github.sha }}"
          token: ${{ secrets.GITHUB_TOKEN }}
